version: '3.4'

services:
  tor-hidden-service:
    container_name: tor-hidden-service
    hostname: tor-hidden-service
    restart: always
    image: ghcr.io/yoanndelattre/tor-hidden-service-docker:main
    environment:
      - APP_NAME=web
      - APP_PORT=80
      - TOR_PORT=80
    volumes:
      - tor-hidden-service_data:/var/lib/tor/hidden_service
    depends_on:
      - web
  web:
    container_name: web
    hostname: web
    restart: always
    image: nginx:alpine

volumes:
  tor-hidden-service_data:
